### ISSUE TITLE
Requires Go 1.4+

### ISSUE THREAD

**Issue by natefinch** [caarlos0/env#1]
So, the problem with aliasing the os.Unsetenv is that it didn't exist until go 1.4. Which means people using earlier versions of go can't use your library as-is.

If it were me, I'd just remove the aliases, but at least you should mention in the readme the min version required of Go.

**Comment by caarlos0** [comment]
I guess I can set the variable to empty instead of using Unsetenv... what do you think?

**Comment by natefinch** [comment]
I don't think that's a good solution, since that will work differently than unsetenv does from the os package.  My advice would be to just not alias the functions from os.  Otherwise, the best option would be to copy the implementation from os.Unsetenv.

**Comment by caarlos0** [comment]
@natefinch makes sense....

Thanks!

**Comment by caarlos0** [comment]
Done in #3, thanks!
