### ISSUE TITLE
curl-like syntax for reading values from file

### ISSUE THREAD

**Issue by mrVanboy** [caarlos0/env#102]
Hi,
we are using your library a lot and it's awesome! 

The only thing which is missing for us is handling secrets from a file. Personally I like the syntax used by `curl` tool which allows reusing the same flag for providing raw body or for the reading body from the file if the value has `@` prefix.

Does it make sense to have similar feature in this package?

Not sure actually if it is desired default behavior, but it could be specified via additional tag:

```go 
type config struct {
	DatabaseUsername      string        `env:"DB_USER"`
	DatabasePassword      string        `env:"DB_PASSWORD", envFilePrefix:"@"`
}
```

<details>
<summary>Usage example [collapsed]</summary>

```go
package main

import (
	"fmt"
	"io/ioutil"
	"os"

	"github.com/caarlos0/env/v6"
)

type config struct {
	DatabaseUsername string `env:"DB_USER"`
	DatabasePassword string `env:"DB_PASSWORD", envFilePrefix:"@"`
}

func main() {
	cfg := config{}
	os.Setenv("DB_USER", "john_doe")

	{
		os.Setenv("DB_PASSWORD", "qwerty123")
		_ = env.Parse(&cfg)
		fmt.Printf("Values without file expansion:\t %+v\n", cfg)
		// Output:
		// Values without file expansion:	 {DatabaseUsername:john_doe DatabasePassword:qwerty123}
	}
	{
		os.Setenv("DB_PASSWORD", "@db_secrets.txt")

		p := []byte("asdfg456")
		_ = ioutil.WriteFile("db_secrets.txt", p, 0644)

		cfg := config{}
		_ = env.Parse(&cfg)

		fmt.Printf("Values with file expansion:\t %+v\n", cfg)
		// Output:
		// Values with file expansion:	 {DatabaseUsername:john_doe DatabasePassword:asdfg456}
	}
}
```

</details>

**Comment by caarlos0** [comment]
The same thing could be accomplished by adding an `if strings.HasPrefix("@")` and etc on the place you are loading the config...

I want to leave this lib as simple and easy to use as possible :) 

["Yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), so, I rather not do this - or at least not right now.

Thanks for the suggestion either way.
