### ISSUE TITLE
env prefix for reusing config objects

### ISSUE THREAD

**Issue by talbspx** [caarlos0/env#104]
it would be nice to have a feature that adds in an env prefix for reusing structs.
for example lets say i have the following Connection Config object in a common module
```go
type ServiceConnectionConfig struct {
     host `env:"HOST" envDefault:"localhost"`
}
```

and now i have a service config object that wants to use this config object -
```go
type ServiceConfig struct {
    ServiceAHost  *common.ServiceConnectionConfig `envPrefix:"SERVICEA_"`
    ServiceBHost  *common.ServiceConnectionConfig `envPrefix:"SERVICEB_"`
}
```

The service that uses ServiceConfig will have to supply these environment variables:

- SERVICEA_HOST

- SERVICEB_HOST

**Comment by caarlos0** [comment]
already had a bunch of issues like this, don't want to implement this.

https://github.com/caarlos0/env/issues?q=is%3Aissue+prefix+is%3Aclosed

**Comment by talbspx** [comment]
for anybody looking for this feature - enjoy
https://github.com/talbspx/env
