### ISSUE TITLE
int32 is not supported after all?

### ISSUE THREAD

**Issue by vegarsti** [caarlos0/env#114]
Thanks for making a great tool!

The following test breaks for me: I can't parse `int32`s. But `int64` works. I'm on `v3.5.0`.

```go
package main

import (
	"os"
	"testing"

	"github.com/caarlos0/env"
)

type A struct {
	A int32 `env:"A,required"`
}

func Test__A(t *testing.T) {
	os.Setenv("A", "12")
	config := A{}
	if err := env.Parse(&config); err != nil {
		t.Errorf("Could not unmarshal config from environment variables: %s", err)
	}
}
```

I do see that there are tests using `int32`, though. Am I simply using it wrong?

Anything I can do to help?

**Comment by caarlos0** [comment]
>  I'm on `v3.5.0`.

latest is v6, which works. I think that might be the issue.

Closing, but feel free to comment...

**Comment by vegarsti** [comment]
Oh, really? That's embarrassing. Thanks for replying

**Comment by caarlos0** [comment]
No problem at all, sorry for the delay in doing so :)
