### ISSUE TITLE
envDefault doesn't satisfy the required constraint

### ISSUE THREAD

**Issue by hebime** [caarlos0/env#115]
I'm not sure if this is by design or a bug but if you specify a field as `required` and set an `envDefault` value, it returns error when trying to parse the environment.

The issue is this check [here](https://github.com/caarlos0/env/blob/master/env.go#L192).
It checks if the env var exists but not the actual value of the variable so a non existing env var will cause it to return an error even though a value has been assigned.

If this is a bug I would be happy to make a PR to fix it.

**Comment by caarlos0** [comment]
I think its a bug indeed, and I would gladly accept a PR.

Thanks!

**Comment by hebime** [comment]
@caarlos0 sorry I missed your message :(
@nuttmeister thanks for fixing it in your PR.
