### ISSUE TITLE
required should return error when value is empty 

### ISSUE THREAD

**Issue by shaj13** [caarlos0/env#133]
I'm not sure if this is by design or a bug but if you specify a field as required and set env with empty value no errors returned 
I have expected an error returned if the value is empty. 

```go
func main() {

	c := &struct {
		LOG string `env:"LOG,required"`
	}{}

	err := env.Parse(c)
				
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("Log Level changed to %s", c.LOG)
}
```

```sh
go run main.go
2020/07/21 00:45:43 env: required environment variable "LOG" is not set
exit status 1 
```

```sh
LOG='' go run main.go
2020/07/21 00:46:10 Log Level changed to
```
related to. 
https://github.com/caarlos0/env/blob/master/env.go#L226

**Comment by shaj13** [comment]
@caarlos0 PTAL, I can fix if it's relevant.

**Comment by caarlos0** [comment]
I think we should, yes, since most people would expect it to fail in that case...

thanks @shaj13

**Comment by ctoyan-via** [comment]
Any update on that @caarlos0 ? :)

**Comment by caarlos0** [comment]
I think this will need to be on a new major, holding for a bit to see if I can do another breaking change together

**Comment by caarlos0** [comment]
maybe to avoid a new major, add a new `notEmpty` tag? wdyt?
