### ISSUE TITLE
Parse environment options should support overrides configuration along with os enivronments

### ISSUE THREAD

**Issue by oriser** [caarlos0/env#138]
I would like the library will support overriding part of the environment variables and the rest will be parsed from the real environment variables.
For example:
```go
package main

import (
	"fmt"
	"github.com/caarlos0/env"
)

type Args struct {
	A string `env:"A"`
	B string `env:"B"`
}

func main() {
	args := &Args{}

	if err := env.Parse(args, env.Options{Environment: map[string]string{"A": "foo"}}); err != nil {
		panic(err)
	}
	fmt.Printf("%#v\n",args)
}
```

Running with: `B=bar go run main.go`

Will output: `&main.Args{A:"foo", B:""}`
I would expect it will output: `&main.Args{A:"foo", B:"bar"}`

**Comment by caarlos0** [comment]
Env is meant to be simple. I'm trying not to add new features unless they can't be achieved in some other way.

On top of that, this would be a breaking change.

That being said, rather not add this right now.

Thanks for the issue and the PR though :)
