### ISSUE TITLE
I got \n character on string suffix with file tag

### ISSUE THREAD

**Issue by mohsensamiei** [caarlos0/env#154]
Hi
I read Postgres connection url from file, sometimes I get this error:
```
postgresql://postgres:postgres@postgres/scms?sslmode=disable\\n: invalid control character in URL
```
Bu I don't have any return or space character after this text in my file

**Comment by caarlos0** [comment]
env doesn't add anything to any env key/value, if thats coming up its because its there...

if you want to be extra sure debug with `fmt.Print(os.Getenv("DATABASE_URL"))`

**Comment by mohsensamiei** [comment]
> env doesn't add anything to any env key/value, if thats coming up its because its there...
> 
> if you want to be extra sure debug with `fmt.Print(os.Getenv("DATABASE_URL"))`

it's ok, but in some environment we might have any invalid character in env
my suggestion is: trim spaces of env value
