### ISSUE TITLE
Need help understanding how to use the custom parser

### ISSUE THREAD

**Issue by marianina8** [caarlos0/env#158]
I have a Metadata type that is defined by pulling in values from different environment variables.  There's one type on the struct that is of a custom Tag type which consists of a key and value.  

```
(root) ~ # echo $ENV_TAGS
[{"foo1":"bar1"},{"foo2":"bar2"}]
```

```go
type Metadata struct {
	ID string `env:"ENV_ID" json:"id,omitempty"`
	Tags             []Tag        `env:"ENV_TAGS" json:"tags,omitempty"`
}

type Tag struct {
	Key   string `json:"key,omitempty"`
	Value string `json:"value,omitempty"`
}

func (i *Metadata) Parse() error {
	var v string
	metadataParser := env.ParserFunc(parseMetadata)
	metadataType := reflect.TypeOf((*Metadata)(nil))
	customParsers := env.CustomParsers{}
	customParsers[instanceMetadataType] = instanceMetadataParser
	if err := env.ParseWithFuncs(&i, customParsers); err != nil {
		return err
	}
	return nil
}

func parseMetadata(metadataJSON string) (Metadata, error) {
	return Metadata{}, nil
}
```

Where metadataParser is defined, I'm getting the following error message: `cannot convert ParseMetadata (value of type func(metadataJSON string) (Metadata, error)) to env.ParserFunc`. Any help would be greatly appreciated!  I need to get past the error message, and I simply need to use the custom parsers to set the environment variables to the proper fields and convert the map[string]string(s) of key-value pairs into a slice of Tags with the Metadata Type.

**Comment by caarlos0** [comment]
There is an example in the tests:

https://github.com/caarlos0/env/blob/master/env_test.go#L732-L769

**Comment by caarlos0** [comment]
closing as no response since months ago...
