### ISSUE TITLE
golangci-lint configuration is ignored

### ISSUE THREAD

**Issue by vfaronov** [caarlos0/env#169]
It looks like you wanted to configure golangci-lint with a `.golangci.yml` file, but made a typo and called the file [`.gorelangci.yml`](https://github.com/caarlos0/env/blob/master/.gorelangci.yml) instead. Your `enable-all: true` in that file is ignored. If you rename the file to `.golangci.yml`, the linters are activated and report many warnings.

**Comment by caarlos0** [comment]
oh, thanks for spotting that!
