### ISSUE TITLE
PR propose

### ISSUE THREAD

**Issue by franciscocpg** [caarlos0/env#17]
Hi @caarlos0.
I'd like to propose a PR for supporting Duration Fields using [ParseDuration](https://golang.org/pkg/time/#ParseDuration) method.
Do you have interest in this work?

**Comment by caarlos0** [comment]
@franciscocpg I think it would be a nice addition... feel free to open it :)

**Comment by franciscocpg** [comment]
Thank you @caarlos0 
Here it is: https://github.com/caarlos0/env/pull/18
