### ISSUE TITLE
Prefix for fields

### ISSUE THREAD

**Issue by jgustie** [caarlos0/env#200]
I have a situation where I would like to reuse a type multiple times in my configuration, it would be nice if fields could specify a prefix to be applied to all of the environment variable names encountered during the recursive processing. For example:

```
type Config struct {
  Home string `env:"HOME"`
}
type ComplexConfig struct {
  Foo Config `envPrefix:"FOO_"`
  Bar Config `envPrefix:"BAR_"`
}
...
cfg := ComplexConfig{}
_ = env.Parse(&cfg, Options{Environment: map[string]string{"FOO_HOME":"/foo","BAR_HOME":"/bar"}})
// cfg.Foo.Home == "/foo" && cfg.Bar.Home == "/bar"
```

**Comment by caarlos0** [comment]
that sounds reasonable, yeah

**Comment by caarlos0** [comment]
check #201
