### ISSUE TITLE
I wrote a code generator that will generate functional options from the env struct

### ISSUE THREAD

**Issue by advanderveer** [caarlos0/env#207]
I use your package in almost all my project, hats-off to making it so simple , to-the-point and useful! 

But what commonly happens is that I want to take the resulting struct and then pass it on to a constructor. This constructor often takes a variadic argument of options (the functional options pattern). Turning a parsed struct of environment variables into these functional options forced me to write a lot of boilerplate code. So I created a code generator: https://github.com/fxlib/envopts

Maybe this is useful to someone else! Let me know if you have any feedback!

**Comment by caarlos0** [comment]
looks neat, thanks for sharing!
