### ISSUE TITLE
Option for default prefix for nested structs

### ISSUE THREAD

**Issue by DeadlySurgeon** [caarlos0/env#209]
It would be nice if there was an option for assuming a default prefix for nested structs. Our usecase has every nested struct having a prefix, coming from https://github.com/kelseyhightower/envconfig, so having to amend everything with `envPrefix:"<Name>_"` is a bit bloated.

**Comment by caarlos0** [comment]
rather keep the library API simpler, a little repetition in this case seem harmless enough.

["Yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), so, I rather not do this - or at least not right now.

Thanks for the suggestion either way.

**Comment by DeadlySurgeon** [comment]
>  a little repetition in this case seem harmless enough

Every single configuration we have, basically has it. It's not a little, in most projects, it tends to be a lot. In our case, +200 lines.
