### ISSUE TITLE
FR: Add Function to SetEnv from a *struct

### ISSUE THREAD

**Issue by mattysweeps** [caarlos0/env#213]
It would be nice if there was an inverse to `env.Parse()`. Something like `env.Set(interface{})` which would take a struct pointer and set environment variables.

The use case for this would be
1. Read env vars into a struct
2. Override some fields in the struct (command line options, for example)
3. Write out the env vars, including the overrides

**Comment by caarlos0** [comment]
I believe that's out of the scope of this lib.
