### ISSUE TITLE
default struct pointer to nil

### ISSUE THREAD

**Issue by jack-evans** [caarlos0/env#217]
I am after the use case where I want some of the config to be nil in certain cases. For example:

```go
type (
  dbConfig {
    hostname string `env:"DB_HOSTNAME"`
  }

  cacheConfig {
    hostname string `env:"CACHE_HOSTNAME"`
  }

  Config {
    CacheConfig *cacheConfig
    DbConfig *dbConfig
  }
)

func main() {
  cfg := &Config{}
  _ = env.Parse(cfg)

  if cfg.CacheConfig != nil {
    // initialise cache here with cacheConfig values
    // if nil we are not using a cache and will only talk to the database 
  }
  
  // initialise DB here
}
```

currently this doesn't seem possible, in all examples I can see in the `Config` struct you have to initialise the `CacheConfig` property before running `env.Parse()` and if you don't then even if the values are set they wont get picked up in the struct

**Comment by caarlos0** [comment]
yeah, that's probably not happening.

I would recommend checking against emptyness of some property in the struct.
