### ISSUE TITLE
Doesn't seem to error out if env isn't set, even if required is set

### ISSUE THREAD

**Issue by dknz2008** [caarlos0/env#220]
I've noticed that it doesn't error out if you don't provide an env, even if `required` is set. Might be worth looking into

**Comment by caarlos0** [comment]
there's a test for it, and its passing.

https://github.com/caarlos0/env/blob/832c913318cc0ac1b4af074c9b0a77eb03225a69/env_test.go#L696-L701

can you provide an example?

**Comment by dknz2008** [comment]
Apologies, ran a few tests and now working. Must have been an old version
