### ISSUE TITLE
Read from multiple environment variables in order

### ISSUE THREAD

**Issue by oavdeev** [caarlos0/env#237]
Doing some configuration refactors here, and it would be nice to have an option to read from multiple env vars in order, i.e. something like:
```
type Config struct {
	Something string `env:"NEW_SETTING|OLD_SETTING,required"`
}
```

Of course I could have two fields in the struct, but then I still need to add some extra bits of logic manually to ensure one of them is set.

**Comment by caarlos0** [comment]
This feels like a bit too much... the idea of this lib is to be simple, so I try to not add new features.

thanks for the suggestion, though!

cheers
