### ISSUE TITLE
New feature: custom method to fetch env

### ISSUE THREAD

**Issue by emilien-puget** [caarlos0/env#239]
Hello, would you be interested in having a way to register a function to fetch a value from somewhere

i imagine this with the ability to have an option to change the method now called `getOr`, with the current implementation being the default one.

My present use case is to fetch informations from a vault-like external service

**Comment by caarlos0** [comment]
hey, @emilien-puget , thanks for the suggestion, but I really like to keep the lib simple, so, rather not add this unless we really, really need to.
