### ISSUE TITLE
import github.com/caarlos0/env  in unit test

### ISSUE THREAD

**Issue by medyagh** [caarlos0/env#25]
I was wondering if you could change this line ? so it doesnt use old code in github when you make a PR ?
https://github.com/caarlos0/env/blob/master/env_test.go#L9

I tried to change to  
`import env`

but travis is not happy with it ...any idea what is the best way to make the PR pass the test?

**Comment by caarlos0** [comment]
Maybe you're cloning the repo in the wrong place?

It must be in `$GOPATH/src/github.com/caarlos0/env`

**Comment by medyagh** [comment]
oh yeah you are right, I did it in src/env

**Comment by caarlos0** [comment]
That's the problem :)
