### ISSUE TITLE
ParseWithOptions not returning error from custom function

### ISSUE THREAD

**Issue by flohoss** [caarlos0/env#268]
Hi,

i am trying to work this out for a while now. The main goal is to parse a shoutrrr url from envs.

I could just create a sender with a string that has been parsed and check for error there. But i would like to use the FuncMap for custom parsing. What am i doing wrong?

 - Is the required param ignored even though i am setting the env to ""?
 - Why is the error that exists in line 21 not recognized in line 34?

The code is based on the [the example](https://pkg.go.dev/github.com/caarlos0/env/v8#example-ParseWithOptions)

[https://play.golang.com/p/4h5IqZLB0Hs](https://play.golang.com/p/4h5IqZLB0Hs)
```go
package main

import (
	"log"
	"os"
	"reflect"

	"github.com/caarlos0/env/v8"
	"github.com/containrrr/shoutrrr"
	"github.com/containrrr/shoutrrr/pkg/router"
)

type config struct {
	// is required ignored, even though the pointer is nil?
	Sender *router.ServiceRouter `env:"NOTIFICATION_URL,required"`
}

func main() {
	os.Setenv("NOTIFICATION_URL", "")

	_, err := shoutrrr.CreateSender(os.Getenv("NOTIFICATION_URL"))
	if err != nil {
		log.Println(err)
	}

	cfg := config{}
	err = env.ParseWithOptions(&cfg, env.Options{
		OnSet: func(tag string, value interface{}, isDefault bool) {
			log.Printf("Set %s to '%s' (default? %v)\n", tag, value, isDefault)
		},
		FuncMap: map[reflect.Type]env.ParserFunc{
			reflect.TypeOf(router.ServiceRouter{}): func(v string) (interface{}, error) {
				// Same as in line 21
				return shoutrrr.CreateSender(v)
			},
		},
	})
	if err != nil {
		log.Fatal(err)
	}
}
```

When run with debugger and NOTIFICATION_URL not set, the error returned from `ParseWithOptions()` is not nil:
`error(github.com/caarlos0/env/v8.AggregateError) {Errors: []error len: 1, cap: 1, [*(*error)(0x1400017c320)]}`
But as soon as the env is set, but empty, no error is returned...

**Comment by flohoss** [comment]
Found the Problem with the debugger:

I was relying on the docs [here](https://pkg.go.dev/github.com/caarlos0/env/v8#example-ParseWithOptions)

But as seen in this function
https://github.com/caarlos0/env/blob/787f006dd70cfc4fb2a58c63ebfbd55f4ea5d7fb/env.go#L185

the error returned is of type `AggregateError` and therefore err != nil does not work here.

https://github.com/caarlos0/env/blob/787f006dd70cfc4fb2a58c63ebfbd55f4ea5d7fb/error.go#L19

Suggestion to change the [ParseWithOptions](https://pkg.go.dev/github.com/caarlos0/env/v8#ParseWithOptions) example to check for `AggregateError`

**Comment by caarlos0** [comment]
have you tried this? https://github.com/caarlos0/env#not-empty-fields

**Comment by caarlos0** [comment]
ahh I see what you mean, regardless of that, the error from the custom parser does not bubble up.

nice, thanks for reporting, will take a look.

fwiw, minimal reproducible: https://play.golang.com/p/ijP_1MxhRp7

**Comment by akutuev** [comment]
@caarlos0, should I take a look if I find time?

**Comment by caarlos0** [comment]
see https://github.com/caarlos0/env/pull/269

**Comment by caarlos0** [comment]
ok, after looking into this again, this is the expected behavior:

- `required` means that the env needs to be set, not empty
- if env is set but empty, the field will have its default value

if you want this to fail, you can set `notEmpty` instead of `required`.
