### ISSUE TITLE
Base64 decode

### ISSUE THREAD

**Issue by manuelarte** [caarlos0/env#278]
Is it possible to have something like this:

```
type Prop struct {
  Password byte[] `env:"PASSWORD,base64"`
}
```

So that env variable PASSWORD is set in base64, but it's decoded in Prop.Password.

**Comment by caarlos0** [comment]
you can do that by implementing `encoding.TextUnmarshaler`:


see example at fd0f7828ec8d80541a738ca31756ff61cfb7788a

**Comment by manuelarte** [comment]
Thanks for your response
