### ISSUE TITLE
expand from default values

### ISSUE THREAD

**Issue by kriptor** [caarlos0/env#279]
Hi,

for example, if you have the following struct
```
type config struct {
	Home       string   `env:"MY_HOME"            envDefault:"/tmp"`
	TempFolder string   `env:"TEMP_FOLDER,expand" envDefault:"${MY_HOME}/temp"`
}
```
and there are no environment variables when you start the process. It would still be nice if you had an option to get `Home: "/tmp"` and `TempFolder: "/tmp/temp"`, wouldn't it? I mean, we did specify what the defaults are :)

If `expand` shouldn't be used like that, maybe `expandWithDefaults` could be.

Cheers!

**Comment by caarlos0** [comment]
happy to review a PR for that :)
