### ISSUE TITLE
Pointer type support

### ISSUE THREAD

**Issue by empirefox** [caarlos0/env#29]
I have a global var `Dev`, but i want to use it in submodule only when submodule's `Config.Dev` is not set, so i must use `*bool`, can you support this?
Thanks!

```go
package main

import (
	"github.com/caarlos0/env"
	"github.com/golang/glog"
)

type Config struct {
	Dev *bool `env:"DEV"`
}

func main() {
	config := new(Config)
	err := env.Parse(config)
	glog.Errorln(config.Dev, err)
}
```

output:
```
<nil> Type is not supported
```

**Comment by caarlos0** [comment]
Hi @empirefox ,

I don't understand why it need to be a pointer.. can you elaborate? How would you pass that as a environment variable?

**Comment by empirefox** [comment]
Here is the config.go
```go
package config

type Server struct {
	Host      string
	Port      int    `env:"PORT"`
	Dev       bool   `env:"DEV"` // this is the global dev setting
}

type Clog struct {
	Dev       *bool  `env:"ZAP_DEV"` // this is submodule dev setting
	DSN       string
	ModuleKey string
}
```
Use case:
- `./main` => `Server.Dev==false Clog.Dev == nil`, then i can fallback `Clog.Dev = *false`.
- `DEV=true ./main` => `Server.Dev==true Clog.Dev == nil`, then i can fallback `Clog.Dev = *true`.
- `ZAP_DEV=true ./main` => `Server.Dev==false Clog.Dev == *true`.
- `DEV=true ZAP_DEV=false ./main` => `Server.Dev==true Clog.Dev == *false`.

I suggest the pointer value should not equal nil only when `os.LookupEnv` detect the variable present and the variable can be converted to the target value.

**Comment by caarlos0** [comment]
I still don't get why it needs to be a pointer.

It also feels misleading as the environment never change once the app is running... 

Maybe you are passing the configs around and changing them? If so, maybe you need to pass a pointer of the struct itself ...

**Comment by empirefox** [comment]
If `Clog.Dev` is not a pointer, then its value will always be false if `ZAP_DEV` is not set, so i don't konw i should fallback its value to `Server.Dev` or it is just set to false. Sorry for my ugly english.

**Comment by empirefox** [comment]
If nil value is enabled, it can tell me whether the variable is present, otherwise the value will always be set to default when the variable is not present. Without nil it is hard to implement the use case above.

**Comment by caarlos0** [comment]
hmmm, now I get it...

For now, you can hack around it by using string instead of bool :)

**Comment by empirefox** [comment]
Thanks @caarlos0 , i'll take your hacking suggestion to make things work first :)

**Comment by medyagh** [comment]
I also think adding pointer is not a good idea. It will break KISS

**Comment by caarlos0** [comment]
Let's close this then.

Thanks everybody!
