### ISSUE TITLE
Add a `ParseFile` function

### ISSUE THREAD

**Issue by imperfect-fourth** [caarlos0/env#292]
A lot of the times, environment variables are stored in a `.env` file. It would be great to have a function `ParseFile` that loads the struct values from a given file. Happy to open a PR for this.

**Comment by caarlos0** [comment]
there are many libs that load .env file to os.environ, which env can then use to parse to a struct...

I'm not sure I see a good reason to add this here as well...

**Comment by caarlos0** [comment]
["Yes is forever"](https://twitter.com/solomonstre/status/715277134978113536), so, I rather not do this - or at least not right now.

Thanks for the suggestion either way.
