### ISSUE TITLE
UseFieldNameByDefault resulting in incorrect Field Name

### ISSUE THREAD

**Issue by tomaszbk** [caarlos0/env#304]
given these config:
```
type Config struct {
	BACKEND_URL   string `envDefault:"localhost:8000"`
}
```
and using:
`opts := env.Options{UseFieldNameByDefault: true}`
My app crashes because it cant find the env var BACKENDURL. I think the underscore should be kept given that it is the convention for writing env vars

**Comment by caarlos0** [comment]
you're correct that that is the convention for environment variable names, but it's not the convention for struct fields.

If you do instead:

```go
type Config struct {
	BackendURL   string `envDefault:"localhost:8000"`
}
```

it'll get the name you expect.

I just pushed some documentation improvements around that, and a test to show how it works:

* a3551ca
* 1e2d9e1
