### ISSUE TITLE
Add a way to optionally create custom deserializers

### ISSUE THREAD

**Issue by cking** [caarlos0/env#33]
Like the title says, it would be awesome to add a way to register cutom deserializers, o you could for example overwrite existing type deserializers (based ons truct texts) to support e.g. json, or for new (complex) types.

**Comment by caarlos0** [comment]
Hi @cking 

What are the use cases for that? I'm not sure I understood what you want to do...

**Comment by cking** [comment]
Right now, your library can "only" parse the following types:
string, int, uint, int64, bool, float32, float64, []string, []int, []bool, []float32, []float64

It would be awesome, if you could add a method to register your own deserializer with the lib, and a tag to use that deserializer.

That way you could for example add a bit of more complex env vars, like for example JSON objects.

**Comment by dselans** [comment]
My most recent PR adds support for custom deserializers.

See #44

**Comment by caarlos0** [comment]
thanks @dselans =D
