### ISSUE TITLE
Support prefix

### ISSUE THREAD

**Issue by ansel1** [caarlos0/env#35]
Support a variant of Parse which takes a prefix to prepend to the environment variable names.  In other words, something like `Parse(&cfg, "myapp")` would look for environment variables named "MYAPP_VAR1", "MYAPP_VAR2", etc.

**Comment by caarlos0** [comment]
seems like a lot of work to not write `PREFIX_`.

See #38 

Let's keep the library simple :)

**Comment by ansel1** [comment]
There are a few use cases that would benefit from this:
1. cases where multiple instances of an app run on the same host.  You can dynamically configure unique prefixes for each instance so they each read their own set of env vars, without code changes/recompile.
2. libraries which support convenience methods for reading the library's configuration options from the environment.  The app which is using the library can tell the library what prefix to use.  Env var prefixes typically go with an app (as a way of namespacing the apps env vars).  This feature would allow apps to impose a prefix on the library when the app tells the library to read its environment.

A different way of doing this would be a way for this package to read from a struct/map rather than from the global environment variables.  A tricky thing with golang and env vars is that they are only global.  If there was a way to capture a snapshot of the environment, modify it at runtime (e.g. filter by prefix, then strip the prefix off the keys), then this package could have an option to read from that.  This would also make unit tests cleaner:  we have an issue now when we try to write unit tests around code that directly reads from the environment (generally, the code which is directly using this package).  Golang doesn't provide a way to create a sandbox for the test with an isolated environment, so we have to jump through some hoops to ensure the test's side affects don't leak into other tests.

**Comment by caarlos0** [comment]
`os.Environ()` returns a copy of strings representing the environment, in the form "key=value", maybe we could allow passing that down.

This would improve tests as well I guess.

Seems a good mid term for me.
