### ISSUE TITLE
Breaking change with uninitialised pointer fields

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [caarlos0/env#41]
I was using this package to set some fields of a struct, while other fields of the same struct were not controlled using environment variables.

This worked fine, until recently - unfortunately not sure exactly when the change was introduced, but now the following example `main.go`

``` go
package main

import (
	"github.com/caarlos0/env"
	"log"
	"net/http"
)

type Session struct {
	Token      string `env:"TOKEN"`
	HttpClient *http.Client
}

func main() {
	sess := Session{}
	err := env.Parse(&sess)
	if err != nil {
		log.Fatal(err)
	}
	sess.HttpClient = &http.Client{}
}
```

produces the output
``` bash
$ go run main.go
2017/11/21 10:57:04 Expected a pointer to a Struct
exit status 1
```

but used to work just fine.

Now maybe it was coincidence that it worked just fine - maybe the package doesn't support structs that have fields that are not supposed to be handled by env vars.

But if it is supposed to be a feature (and I think at least I would like it to be ^^), then the above is probably a bug.

A workaround, btw, is to move the assignment before the parsing, as in 

``` go
	sess := Session{}
	sess.HttpClient = &http.Client{}
	err := env.Parse(&sess)
```

This won't throw an error.

**Comment by belimawr** [comment]
I also run on the same problem. I've got some fields not managed by environment variables, and they're pointer to structs.

My suggestion:
 * Don't try to parse fields without the ``env`` struct tag

**Comment by caarlos0** [comment]
/remind me fix this issue in 6 hours

**Comment by caarlos0** [comment]
Oh my...

/remind me really fix this in 8 hours

**Comment by valentin-krasontovitsch** [comment]
Thanks, much appreciated! = )
