### ISSUE TITLE
panic: reflect: reflect.Value.Set using value obtained using unexported field

### ISSUE THREAD

**Issue by dumindu** [caarlos0/env#82]
It's mandatory to use exported fields on the struct, which we need to parse. We should able to use unexported fields as well.

**Steps to reproduce**
- Use https://github.com/caarlos0/env#example
- Rename `Home` field of `config` struct to `home` (Line 11)
- run `PRODUCTION=true HOSTS="host1:host2:host3" DURATION=1s go run main.go`

**Expected**
-  output `{Home:/your/home Port:3000 IsProduction:true Hosts:[host1 host2 host3] Duration:1s}`

**Actual**
```
panic: reflect: reflect.Value.Set using value obtained using unexported field

goroutine 1 [running]:
reflect.flag.mustBeAssignable(0x1b8)
        /usr/local/go/src/reflect/value.go:231 +0x1bd
```

**Comment by caarlos0** [comment]
AFAIK reflect won't allow to set on unexported fields... shouldn't panic though, fixing...

**Comment by dumindu** [comment]
Thanks for the quick response and for the patch.

**Comment by dumindu** [comment]
Tried `go get -u github.com/caarlos0/env@v5.0.1`, go.mod and sum files were updated with `v0.0.0` instead `v.5.0.1`
ex, `github.com/caarlos0/env v0.0.0-20190429102911-1ef39d30b036 // indirect`

might be an issue on my side. Just informed btw :)

**Comment by caarlos0** [comment]
🤔

**Comment by caarlos0** [comment]
let me test this as well

**Comment by caarlos0** [comment]
don't know why... its happening to me too... even recreated the tag and etc :/

**Comment by caarlos0** [comment]
seems like v4.0.0 also don't work as expected...

**Comment by caarlos0** [comment]
@dumindu fixed on v5.1.3, thanks for pointing it out!

**Comment by caarlos0** [comment]
PS: if you're using go mods, `go get -u go get -u github.com/caarlos0/env/v5` should do the trick :)

**Comment by dumindu** [comment]
@caarlos0 Looks like something is wrong in the fix,

Used the same code in https://github.com/caarlos0/env#example
- With exportable fields
```
PRODUCTION=true HOSTS="host1:host2:host3" DURATION=1s go run main.go
{Home:/Users/my_name Port:3000 IsProduction:true Hosts:[host1 host2 host3] Duration:1s TempFolder:/Users/my_name/tmp}
```

- With unexportable fields
```
PRODUCTION=true HOSTS="host1:host2:host3" DURATION=1s go run main.go
{home: port:0 isProduction:false hosts:[] duration:0 tempFolder:}
```

**Comment by caarlos0** [comment]
yes, it just ignores unexported fields, same behavior as encoding/json, so the values will be the language defaults (empty string, 0 number, false bool, empty slices etc)

**Comment by dumindu** [comment]
@caarlos0 so is this the expected behavior?

**Comment by caarlos0** [comment]
> I think lib should support for unexportable fields as well.

AFAIK Go won't allow you to change unexported fields in another package via reflection...
