### ISSUE TITLE
Broken go.mod

### ISSUE THREAD

**Issue by rkuska** [caarlos0/env#86]
It looks like this commit broke the go.mod file:

https://github.com/caarlos0/env/commit/0b4f1fc4774952aad2a0e3d796bf446cc294960d

Latest working version that I can update to and go mod tidy goes through is 5.1.1, 5.1.2 fails with following message:

`go: github.com/caarlos0/env@v5.1.2+incompatible: go.mod has post-v5 module path "github.com/caarlos0/env/v5" at revision v5.1.2`

caarlos0/env is listed as `github.com/caarlos0/env v5.1.1+incompatible` in my go.mod file (upgrading from v4).

**Comment by caarlos0** [comment]
you need to change the import to `github.com/caarlos0/env/v5`, unfortunately that's how go modules work... 

more info: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by rkuska** [comment]
Interesting, I thought it is needed to specify major version in import only if you use multiple such versions.

**Comment by caarlos0** [comment]
> Interesting, I thought it is needed to specify major version in import only if you use multiple such versions.

yeah, seems like not... anything greater than v1 needs that.

I particularly don't like it very much, but 🤷‍♂️

**Comment by caarlos0** [comment]
I actually already added it to docs: https://github.com/caarlos0/env#go-modules

**Comment by rkuska** [comment]
Didn't notice that one, sorry! Thank you and sorry for the false issue, closing this :-)

**Comment by caarlos0** [comment]
no problem, thanks! :D

**Comment by caarlos0** [comment]
btw: fixed on https://github.com/caarlos0/env/releases/tag/v6.0.0

<blockquote><img src="https://repository-images.githubusercontent.com/39808208/08c89e00-672f-11e9-87b9-8c38e7565a94" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/caarlos0/env">caarlos0/env</a></strong></div><div>Simple lib to parse envs to structs. Contribute to caarlos0/env development by creating an account on GitHub.</div></blockquote>
