### ISSUE TITLE
Support UnmarshalText interface

### ISSUE THREAD

**Issue by johanbrandhorst** [caarlos0/env#87]
Hi, I saw this library on the gophers slack and the one thing I think it's missing for me is the ability to support types that implement the [`TextUnmarshaler`](https://golang.org/pkg/encoding/#TextUnmarshaler) interface out of the box, like https://github.com/kelseyhightower/envconfig does.

**Comment by caarlos0** [comment]
it already does:

- https://github.com/caarlos0/env/blob/master/env_test.go#L23
- https://github.com/caarlos0/env/blob/master/env_test.go#L110-L113
- https://github.com/caarlos0/env/blob/master/env_test.go#L148-L151

**Comment by johanbrandhorst** [comment]
Ah great, then we should just add it to the README, the current README gives the impression that you need to use a special reflect type mapping.

**Comment by caarlos0** [comment]
let me know if it looks better now!

thanks!

**Comment by johanbrandhorst** [comment]
Fantastic, thanks!

**Comment by hypnoglow** [comment]
Hey.

Not sure if I should open a new issue, but I think priority for interfaces such as TextUnmarshaler should be higher than for primitive types.

Example problem:

```go
type LogLevel int8

func (l *LogLevel) UnmarshalText(text []byte) error {
	txt := string(text)
	switch txt {
	case "debug":
		*l = DebugLevel
	case "info":
		*l = InfoLevel
	default:
		return fmt.Errorf("unknown level: %q", txt)
	}

	return nil
}

const (
	DebugLevel LogLevel = iota - 1
	InfoLevel
)

func main() {
	os.Setenv("LOG_LEVEL", "debug")

	var config struct {
		LogLevel LogLevel `env:"LOG_LEVEL"`
	}

	err := env.Parse(&config)
	if err != nil {
		log.Fatal(err)
	}

	log.Print(config)
}
```

This returns an error: `2019/05/03 20:49:02 env: parse error on field "LogLevel" of type "main.LogLevel": strconv.ParseInt: parsing "debug": invalid syntax`

In contrast, envconfig library mentioned above correctly parses this example config.

Thanks.

**Comment by caarlos0** [comment]
Hey @hypnoglow, thanks for pointing that out!

Just fixed it in https://github.com/caarlos0/env/pull/88

Cheers!

**Comment by hypnoglow** [comment]
@caarlos0 This is awesome, thanks!
