### ISSUE TITLE
Bad import?

### ISSUE THREAD

**Issue by arincon1973** [caarlos0/env#89]
Noticed the import github.com/caarlos0/env/parsers in env.go and env_test.go:
"github.com/caarlos0/env/v5/parsers"
should it be:
"github.com/caarlos0/env/parsers" instead?

**Comment by caarlos0** [comment]
no, its required for go modules.

if you're using dep, you may keep v4 or less.

https://github.com/caarlos0/env#go-modules

**Comment by caarlos0** [comment]
btw: fixed on https://github.com/caarlos0/env/releases/tag/v6.0.0
