### ISSUE TITLE
Recursive struct parsing does not use `CustomParsers`

### ISSUE THREAD

**Issue by paper-lark** [caarlos0/env#90]
Custom parsers passed to `ParseWithFuncs` are not used when parsing pointers in the struct.

**Comment by caarlos0** [comment]
can you provide an example of this? I'm not being able to reproduce...

**Comment by caarlos0** [comment]
oh. nervermind, just got it

**Comment by paper-lark** [comment]
@caarlos0 yeah, sorry there was no example in the issue description. I just wanted to fix the bug sooner :)

**Comment by caarlos0** [comment]
can you check #93? there is a test for the issue you experienced I think (and also other goodies)

**Comment by caarlos0** [comment]
fixed in #91
