### ISSUE TITLE
DefaultEnv reuse across Vars?

### ISSUE THREAD

**Issue by donmstewart** [caarlos0/env#97]
If I have a config struct of ENV vars and the fields are dependant it does not seem to work. i.e.

```go
type envConfig struct {
	Mixin           string `env:"MIXIN" envDefault:"bar"`
	Package      string `env:"PKG" envDefault:"github.com/donmstewart/foo-${MIXIN}" envExpand:"true"`
```

Whilst the `Mixin`field is correct after parsing i.e. `bar` the `Package` field becomes `github.com/donmstewart/foo-` rather than `github.com/donmstewart/foo-bar` in the situation where defaulting occurs.

**Comment by caarlos0** [comment]
not sure if its worth doing that... we parse all envs in a single pass, if we add this for defaults, users would expect it for non defaults as well...

you can try a PR and we can see how it looks... but I think it will be ugly 🤔

**Comment by caarlos0** [comment]
closing as it seems like 'no'.
